export const PHONE_NUMBER = "9885858529";
export const WHATSAPP_NUMBER = "918585854853";
export const PHONE_HREF = `tel:${PHONE_NUMBER}`;
export const WHATSAPP_HREF = `https://wa.me/${WHATSAPP_NUMBER}`;

export const NAV_LINKS = [
  { label: "Home", href: "#home" },
  { label: "Properties", href: "#properties" },
  { label: "Services", href: "#services" },
  { label: "About", href: "#about" },
  { label: "Contact", href: "#contact" },
];

export const PROPERTIES = [
  // --- First Batch (Featured Properties) ---
  {
    id: 1,
    name: "iWA by SRIAS",
    location: "Nanakramguda",
    type: "3, 3.5, 4 & 4.5 BHK",
    area: "2,290 – 4,710 Sq.Ft.",
    price: "₹9,500/Sq.Ft.",
    possession: "Tower 6 Available",
    rera: true,
    payment: "OTP Payment Only",
    badge: "New Launch",
    highlight: "Tower 6 Available",
    tag: "Nanakramguda",
    image: "/properties/iwa-by-srias.webp",
  },
  {
    id: 2,
    name: "Mango Leaf Villas",
    location: "Osman Nagar",
    type: "3 & 4 BHK Villas",
    area: "2,739 – 3,084 Sq.Ft.",
    price: "OTP Payment Only",
    possession: "Under Construction",
    rera: true,
    payment: "OTP Payment Only",
    badge: "Luxury Villas",
    highlight: "200 – 317 Sq.Yds. Plot",
    tag: "Osman Nagar",
    image: "/properties/mango-leaf-villas.jpg",
  },
  {
    id: 3,
    name: "Linq by Raghava",
    location: "Kokapet",
    type: "3 BHK Premium",
    area: "1,798 – 2,388 Sq.Ft.",
    price: "₹7,500/Sq.Ft.++",
    possession: "4 Years",
    rera: true,
    payment: "OTP Available",
    badge: "Premium",
    highlight: "Gated Community",
    tag: "Kokapet",
    image: "/properties/linq-raghava.png",
  },
  {
    id: 4,
    name: "Prestige Golden Groove",
    location: "Tellapur",
    type: "2, 3 & 4 BHK",
    area: "1,169 – 3,013 Sq.Ft.",
    price: "Call for Price",
    possession: "5 Years",
    rera: true,
    payment: "Loan Available",
    badge: "New Launch",
    highlight: "Premium Township",
    tag: "Tellapur",
    image: "/properties/prestige-golden-groove.webp",
  },
  {
    id: 5,
    name: "Rajpushpa Prestinia",
    location: "Kokapet",
    type: "2 & 3 BHK",
    area: "1,380 – 2,300 Sq.Ft.",
    price: "₹8,999/Sq.Ft.++ - 1.1Cr+",
    possession: "2.5 Years",
    rera: true,
    payment: "One Time Payment",
    badge: "Hot Deal",
    highlight: "1.1 Cr onwards",
    tag: "Kokapet",
    image: "/properties/rajpushpa-prestinia.webp",
  },
  {
    id: 6,
    name: "SSI Fortune Grande",
    location: "Neopolis",
    type: "3.5 & 4 BHK",
    area: "2,850 – 3,910 Sq.Ft.",
    price: "₹8,699/Sq.Ft.+PLC",
    possession: "3.5 Years",
    rera: true,
    payment: "OTP / Loan",
    badge: "Luxury",
    highlight: "Ultra Spacious",
    tag: "Neopolis",
    image: "/properties/ssi-fortune.png",
  },
  {
    id: 7,
    name: "Trilight",
    location: "Kokapet",
    type: "3 & 4 BHK",
    area: "2,888 – 5,777 Sq.Ft.",
    price: "₹11,600/Sq.Ft.+++",
    possession: "2.5 Years",
    rera: true,
    payment: "Loan Available",
    badge: "Ultra Luxury",
    highlight: "Sky Villas",
    tag: "Kokapet",
    image: "/properties/trilight.png",
  },
  {
    id: 8,
    name: "Anvita High9",
    location: "Tellapur",
    type: "2 & 3 BHK",
    area: "1,360 – 2,610 Sq.Ft.",
    price: "₹6,499/Sq.Ft.+FR+Infra",
    possession: "2.5 Years",
    rera: true,
    payment: "One Time Payment",
    badge: "Value Buy",
    highlight: "Smart Homes",
    tag: "Tellapur",
    image: "/properties/anvita-high9.webp",
  },

  // --- Additional Available Properties ---
  {
    id: 9,
    name: "DSR Altitude",
    location: "Tellapur",
    type: "3 BHK Flats",
    area: "2,277 Sq.Ft.",
    price: "₹5,999/Sq.Ft.",
    possession: "3.5 Years",
    rera: true,
    payment: "One Time Payment",
    badge: "Best Value",
    highlight: "1.36 Cr onwards",
    tag: "Tellapur",
    image: "/properties/dsr-altitude.webp",
  },
  {
    id: 10,
    name: "Saanvi Prelaunch",
    location: "Kokapet",
    type: "3 BHK Flats",
    area: "2,100 – 2,500 Sq.Ft.",
    price: "₹6,200/Sq.Ft.",
    possession: "2.5 Years",
    rera: true,
    payment: "One Time Payment",
    badge: "Hot Deal",
    highlight: "1.2 Cr onwards",
    tag: "Kokapet",
    image: "/properties/saanvi-prelaunch.png",
  },
  {
    id: 11,
    name: "Aparna New Lands",
    location: "Tellapur",
    type: "2.5 & 3 BHK Flats",
    area: "1,475 – 1,991 Sq.Ft.",
    price: "₹8,699/Sq.Ft.+",
    possession: "2.5 Years",
    rera: true,
    payment: "35% Payment Now",
    badge: "Premium",
    highlight: "Gated Community",
    tag: "Tellapur",
    image: "/properties/saanvi-prelaunch.png",
  },
  {
    id: 12,
    name: "Vasavi Atlantis",
    location: "Narsingi",
    type: "2 & 3 BHK Flats",
    area: "1,310 – 3,330 Sq.Ft.",
    price: "₹9,299/Sq.Ft.",
    possession: "1 Year",
    rera: true,
    payment: "OTP & 70% Loan",
    badge: "New Launch",
    highlight: "All Inclusive",
    tag: "Narsingi",
    image: "/properties/vasavi-atlantis.webp",
  },
  {
    id: 13,
    name: "Vajra West City",
    location: "Kollur",
    type: "2.5 & 3 BHK Flats",
    area: "1,420 – 2,030 Sq.Ft.",
    price: "₹5,200/Sq.Ft.+PLC",
    possession: "3.5 Years",
    rera: true,
    payment: "OTP Available",
    badge: "Value Buy",
    highlight: "Kollur/Tellapur",
    tag: "Tellapur",
    image: "/properties/vajra-west-city.webp",
  },
  {
    id: 14,
    name: "Anvita Ivana",
    location: "Tellapur",
    type: "2 & 3 BHK Flats",
    area: "1,360 – 4,410 Sq.Ft.",
    price: "₹6,499/Sq.Ft.+FR",
    possession: "2.5 Years",
    rera: true,
    payment: "One Time Payment",
    badge: "Best Value",
    highlight: "2nd Car Parking",
    tag: "Tellapur",
    image: "/properties/anvita-ivana.webp",
  },
  {
    id: 15,
    name: "Moonglade",
    location: "Narsingi",
    type: "2 & 3 BHK Flats",
    area: "1,400 – 3,045 Sq.Ft.",
    price: "₹6,499/Sq.Ft.+PLC",
    possession: "3 Years",
    rera: true,
    payment: "One Time Payment",
    badge: "New Launch",
    highlight: "OTP Available",
    tag: "Narsingi",
    image: "/properties/moonglade.webp",
  },
  {
    id: 16,
    name: "Aparna Cyber4",
    location: "Osman Nagar",
    type: "3 & 4 BHK Flats",
    area: "1,340 – 2,300 Sq.Ft.",
    price: "₹7,700/Sq.Ft.+FR",
    possession: "8 Months",
    rera: true,
    payment: "One Time Payment",
    badge: "Premium",
    highlight: "Near Ready",
    tag: "Osman Nagar",
    image: "/properties/aparna-cyber4.webp",
  },
  {
    id: 17,
    name: "Candeur Crescent",
    location: "Kondapur",
    type: "3 BHK",
    area: "1,500 – 2,600 Sq.Ft.",
    price: "₹8,799/Sq.Ft.",
    possession: "6 Months",
    rera: true,
    payment: "Schedule/OTP",
    badge: "Hot Deal",
    highlight: "Near Ready",
    tag: "Kokapet",
    image: "/properties/candeur-crescent.webp",
  },
  {
    id: 18,
    name: "Hallmark Nature Nest",
    location: "Kollur",
    type: "Villas",
    area: "2,800 – 4,500 Sq.Ft.",
    price: "₹8,999/Sq.Ft.",
    possession: "1 Year",
    rera: true,
    payment: "One Time Payment",
    badge: "Luxury",
    highlight: "180–320 Sq Yards",
    tag: "Tellapur",
    image: "/properties/hallmark-nature-nest.webp",
  },
  {
    id: 19,
    name: "Raghava Cinq",
    location: "Financial District",
    type: "4 BHK Flats",
    area: "3,600 Sq.Ft.",
    price: "₹9,800/Sq.Ft.+",
    possession: "3.5 Years",
    rera: true,
    payment: "Regular Payment",
    badge: "Ultra Luxury",
    highlight: "Premium Location",
    tag: "Nanakramguda",
    image: "/properties/raghava-cinq.webp",
  },
  {
    id: 20,
    name: "4 BHK Villas Kollur",
    location: "Kollur",
    type: "4 BHK Villas",
    area: "200 – 240 Sq Yards",
    price: "₹8,499/Sq.Ft. (OTP)",
    possession: "3.5 Years",
    rera: true,
    payment: "OTP / Loan",
    badge: "Luxury",
    highlight: "Villa Community",
    tag: "Tellapur",
    image: "/properties/villas-kollur.webp",
  },
  {
    id: 21,
    name: "Aparna One",
    location: "Shaikpet",
    type: "3 & 4 BHK Flats",
    area: "2,700 – 5,300 Sq.Ft.",
    price: "₹15,999/Sq.Ft.++",
    possession: "Ready to Move",
    rera: true,
    payment: "Schedule Payment",
    badge: "Ultra Luxury",
    highlight: "Ready to Move",
    tag: "Kokapet",
    image: "/properties/aparna-one.webp",
  },
  {
    id: 22,
    name: "Raghava IRIS",
    location: "Gachibowli",
    type: "4 & 6 BHK Flats",
    area: "5,430 – 11,800 Sq.Ft.",
    price: "₹14,000/Sq.Ft.",
    possession: "2 Years",
    rera: true,
    payment: "One Time Payment",
    badge: "Ultra Luxury",
    highlight: "Raidurgam",
    tag: "Kokapet",
    image: "/properties/raghava-iris.webp",
  },
  {
    id: 23,
    name: "Elegans Homes Villas",
    location: "Kollur",
    type: "4 BHK Villas",
    area: "207 – 293 Sq Yards",
    price: "₹12,999/Sq.Ft.",
    possession: "Ready to Move",
    rera: true,
    payment: "Schedule/OTP",
    badge: "Luxury",
    highlight: "RERA Approved",
    tag: "Tellapur",
    image: "/properties/elegans-homes-villas.webp",
  },
  {
    id: 24,
    name: "Sriven IRIS",
    location: "Narsingi",
    type: "5 BHK Villas",
    area: "350 Sq Yards",
    price: "₹12 Cr (Loan)",
    possession: "Ready to Move",
    rera: true,
    payment: "Loan Available",
    badge: "Ultra Luxury",
    highlight: "Excellent Location",
    tag: "Narsingi",
    image: "/properties/sriven-iris.webp",
  },
  {
    id: 25,
    name: "Rajpushpa Prestinia II",
    location: "Kokapet",
    type: "2 & 3 BHK Flats",
    area: "1,380 – 2,300 Sq.Ft.",
    price: "₹8,399/Sq.Ft.+HR",
    possession: "1.5 Years",
    rera: true,
    payment: "One Time Payment",
    badge: "Hot Deal",
    highlight: "RERA Approved",
    tag: "Kokapet",
    image: "/properties/rajpushpa-prestinia-2.webp",
  },
  {
    id: 26,
    name: "My Home APAS",
    location: "Kokapet",
    type: "3 & 3.5 BHK Flats",
    area: "2,800 – 3,800 Sq.Ft.",
    price: "₹10,800/Sq.Ft.++",
    possession: "1.5 Years",
    rera: true,
    payment: "Progressive/Loan",
    badge: "Premium",
    highlight: "RERA Approved",
    tag: "Kokapet",
    image: "/properties/my-home-apas.webp",
  },
  {
    id: 27,
    name: "SRR River View",
    location: "Narsingi",
    type: "3 BHK Flat",
    area: "1,800 – 3,000 Sq.Ft.",
    price: "₹9,499/Sq.Ft.",
    possession: "6 Months",
    rera: true,
    payment: "60% Loan",
    badge: "Hot Deal",
    highlight: "Best Location",
    tag: "Narsingi",
    image: "/properties/srr-river-view.webp",
  },
];

export const SERVICES = [
  {
    title: "Buy Landlord Share Flat",
    description:
      "Access exclusive landlord-share flats at competitive prices. We verify every document so you can buy with complete confidence and clarity.",
    icon: "Building2",
    color: "from-emerald-500/20 to-emerald-600/5",
    accentColor: "text-emerald-400",
  },
  {
    title: "Sell Your Property",
    description:
      "List your landlord-share or builder floor property with us and connect with thousands of verified, serious buyers instantly.",
    icon: "TrendingUp",
    color: "from-blue-500/20 to-blue-600/5",
    accentColor: "text-blue-400",
  },
  {
    title: "Document Verification",
    description:
      "Our experts verify RERA registration, title deeds, encumbrance certificates, and all legal documents before you sign.",
    icon: "ShieldCheck",
    color: "from-purple-500/20 to-purple-600/5",
    accentColor: "text-purple-400",
  },
  {
    title: "Investment Consulting",
    description:
      "Get personalized investment advice from experienced real estate consultants who understand Hyderabad's micro-markets.",
    icon: "LineChart",
    color: "from-amber-500/20 to-amber-600/5",
    accentColor: "text-amber-400",
  },
  {
    title: "Home Loan Assistance",
    description:
      "We are official affiliate partners with Axis Bank & other leading banks to secure pre-approved home loans with exclusive interest rates and fast approvals.",
    icon: "Banknote",
    color: "from-red-500/20 to-red-600/5",
    accentColor: "text-red-500",
  },
  {
    title: "NRI Property Services",
    description:
      "End-to-end property management and transaction support tailored specifically for Non-Resident Indians.",
    icon: "Gem",
    color: "from-rose-500/20 to-rose-600/5",
    accentColor: "text-rose-400",
  },
];

export const FAQS = [
  {
    question: "What is a landlord share flat?",
    answer:
      "When a landowner partners with a builder to develop land, the builder constructs the building and gives a portion of the completed apartments to the landowner as compensation. These are called landlord share flats. Landowners often sell these flats directly at attractive prices.",
  },
  {
    question: "Are landlord share flats legally safe to buy?",
    answer:
      "Yes, provided all legal documents are verified. The key document is the Joint Development Agreement (JDA) and Sharing Agreement. At LandlordShares, we verify title deeds, RERA approvals, municipal sanctions, and encumbrance certificates before listing any property.",
  },
  {
    question: "Are landlord share flats cheaper than builder flats?",
    answer:
      "In many cases, yes. Landowners may price their share of flats 5% to 15% lower than the builder's official pricing for faster liquidity. However, quality, amenities, and location remain identical to builder units.",
  },
  {
    question: "Can I get a home loan for a landlord share flat?",
    answer:
      "Yes. Major banks like SBI, HDFC, ICICI, and Axis provide home loans for landlord share properties, provided the builder has master project approval and the landowner's share is properly registered and documented.",
  },
  {
    question: "What is LandlordShares' role in the transaction?",
    answer:
      "We act as your trusted property advisor. We curate verified listings directly from genuine landowners, coordinate site visits, assist with legal due diligence, facilitate price negotiation, and guide you through registration and loan approval.",
  },
  {
    question: "How long does the entire purchase process take?",
    answer:
      "The timeline varies by project, but typically: Property shortlisting takes 1–3 days, legal verification takes 3–7 days, loan approval takes 7–15 days, and registration takes 1–3 days after loan disbursement. Our team tracks every step for you.",
  },
  {
    question: "Can NRIs buy landlord share properties through you?",
    answer:
      "Absolutely. We have a dedicated NRI desk that handles digital document verification, video consultations, power-of-attorney arrangements, and remote transaction management. Many of our happy clients are NRIs based in the US, UK, UAE, and Australia.",
  },
  {
    question: "What documents do I need to buy a landlord share flat?",
    answer:
      "Standard documents include Aadhaar card, PAN card, income proof (salary slips or ITR), bank statements (6 months), and passport-size photos. For NRIs, passport and visa copies are additionally required. Our team will guide you through the complete checklist.",
  },
];

export const PARTNERS: { name: string; initials: string; color: string; logo?: string }[] = [
  { name: "Aparna Constructions", initials: "AC", color: "bg-blue-600", logo: "/partners/aparna.png" },
  { name: "Vasavi Group", initials: "VG", color: "bg-amber-600", logo: "/partners/vasavi.png" },
  { name: "Vajra Builders", initials: "VB", color: "bg-purple-600", logo: "/partners/vajra.png" },
  { name: "Anvita Projects", initials: "AP", color: "bg-emerald-600", logo: "/partners/anvita.png" },
  { name: "Rajpushpa Properties", initials: "RP", color: "bg-rose-600", logo: "/partners/rajpushpa.png" },
  { name: "Hallmark Builders", initials: "HB", color: "bg-indigo-600", logo: "/partners/hallmark.png" },
  { name: "Raghava Group", initials: "RG", color: "bg-teal-600", logo: "/partners/raghava.png" },
  { name: "Candeur Landmarks", initials: "CL", color: "bg-orange-600", logo: "/partners/candeur.png" },
  { name: "My Home Group", initials: "MH", color: "bg-sky-600", logo: "/partners/my-home.png" },
  { name: "SRR Holdings", initials: "SR", color: "bg-violet-600", logo: "/partners/srr.png" },
  { name: "DSR Infrastructure", initials: "DI", color: "bg-cyan-700", logo: "/partners/dsr.png" },
  { name: "Prestige Group", initials: "PG", color: "bg-slate-700", logo: "/partners/prestige.png" },
  { name: "SSI Developers", initials: "SS", color: "bg-red-600", logo: "/partners/ssi.png" },
  { name: "Sriven Projects", initials: "SP", color: "bg-lime-700", logo: "/partners/sriven.png" },
  { name: "Elegans Homes", initials: "EH", color: "bg-fuchsia-600", logo: "/partners/elegans.png" },
  { name: "SRIAS Life Spaces", initials: "SL", color: "bg-emerald-700", logo: "/partners/srias.png" },
];

export const AREAS = ["All", "Nanakramguda", "Osman Nagar", "Kokapet", "Tellapur", "Narsingi", "Neopolis"];

